INFO : 2025-02-21 12:36:14,419 : 16_program_on_logging.py : Reached try block
INFO : 2025-02-21 12:36:14,420 : 16_program_on_logging.py : Opening file
INFO : 2025-02-21 12:36:14,420 : 16_program_on_logging.py : Reached except block
ERROR : 2025-02-21 12:36:14,421 : 16_program_on_logging.py : Not able to open file and Reason: [Errno 2] No such file or directory: 'D/asdsa/wewrw.txt'
INFO : 2025-02-21 12:36:14,421 : 16_program_on_logging.py : Reached finally block
ERROR : 2025-02-21 12:36:14,421 : 16_program_on_logging.py : Not able to close file handle and the reason is:name 'my_file_handle' is not defined
